// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azujfsrsrimijexuxkal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6dWpmc3JzcmltaWpleHV4a2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzgyOTAsImV4cCI6MjA2NjQxNDI5MH0.VrJRd8MdcKFOAu7OESSF0WsnssvwNuN3bMphs7Nnuvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);